### ISSUE TITLE
Question about transformation from (10) to (11) 

### ISSUE THREAD

**Issue by empty-id** [lironui/Linear-Attention-Mechanism#1]
Hi, thanks for your brilliant work. I have a question about transformation from (10) to (11) in the paper.

Is it true that "dot product first, then summation" equals to "summation first, then dot product"?

Could you explain it in more details? Thank you!

**Comment by lironui** [comment]
Thanks for your attention, and I think an example will answers your query. Please see the image.
![1596296101611](https://user-images.githubusercontent.com/52184525/89104975-dfc5ab80-d44f-11ea-87d0-b81cd60d85b1.jpg)

**Comment by empty-id** [comment]
However, what if taking $v_j$ into consideration? The product of $q_i^T k_j$ and $v_j$ is actually a broadcast multiplication.

By the way, I think for the image above $q_1 = [1, 4]$ instead of $q_1^T = [1, 4]$, which is also confusing in the paper (the problem of row value or column value).

**Comment by empty-id** [comment]
Yeah, it is true! Thank you! I tried for myself, indeed, it is true.
